### ISSUE TITLE
这个依赖不在维护了吗

### ISSUE THREAD

**Issue by Zhao187** [enbandari/ActivityBuilder#10]
这个依赖不在维护了吗

**Comment by bennyhuo** [comment]
有什么问题直接开issue就行



---原始邮件---
发件人: "Zhao187"<notifications@github.com>
发送时间: 2020年3月2日(周一) 中午11:04
收件人: "enbandari/TieGuanYin"<TieGuanYin@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [enbandari/TieGuanYin] 这个依赖不在维护了吗 (#10)



这个依赖不在维护了吗

**Comment by bennyhuo** [comment]
会继续做的，前一阵子在忙 Kotlin 的视频和书，没顾上。后面抽空把留的坑填一下。应该会优先考虑支持下 AndroidX 和 Gradle 增量编译
