### ISSUE TITLE
项目编译报错

### ISSUE THREAD

**Issue by 751496032** [enbandari/ActivityBuilder#12]
![image](https://user-images.githubusercontent.com/13871838/89261780-3a822180-d661-11ea-8669-470afe3dcff3.png)

项目编译时的报错，jcenter.properties这个文件没有

**Comment by bennyhuo** [comment]
这个文件是我自己的私有文件，你可以自己写一个空的或者注掉发布jcenter的配置

--------------原始邮件--------------
发件人："H.ZWei7 "<notifications@github.com&gt;;
发送时间：2020年8月4日(星期二) 下午2:48
收件人："enbandari/TieGuanYin" <TieGuanYin@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[enbandari/TieGuanYin] 项目编译报错 (#12)
-----------------------------------

 

 

 
项目编译时的报错，jcenter.properties这个文件没有

**Comment by 751496032** [comment]
谢谢，可以了
