### ISSUE TITLE
我想问一下  intent传值传一个bean或者传一个集合这里支持吗

### ISSUE THREAD

**Issue by nanchaodong** [enbandari/ActivityBuilder#2]

**Comment by bennyhuo** [comment]
现在只针对 Intent 支持的数据类型做了处理。如果需要传 Bean 或者 集合，需要做转换，这个可以后续考虑支持 但需要注意的是，Intent 可以传递的数据大小是有限的

**Comment by bennyhuo** [comment]
v2.0-converter 分支上尝试做了对 Bean 的支持，在 App 模块中有 Person、Book 类作为演示，支持嵌套，目前使用反射做数据类型的转换~可以试下

**Comment by bennyhuo** [comment]
感觉 Parcelable 足够使用，不准备对任意类型做支持了。
