### ISSUE TITLE
not work well in single task launch Mode

### ISSUE THREAD

**Issue by huangying812** [enbandari/ActivityBuilder#3]
due to inject invoke time,when an activity is start in single task / instance mode,
new params not in use on "onNewIntent(intent: Intent?)" lifecycle
wait for fix

**Comment by bennyhuo** [comment]
I‘ll check that later.

**Comment by bennyhuo** [comment]
I'll provide a method for that Since the intent passed from onNewIntent cannot be obtained only if you explicitly call setIntent(intent) when onNewIntent called.

**Comment by bennyhuo** [comment]
Try with the version 2.0-beta3:

```java
@Override
public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    MyActivityBuilder.processNewIntent(this, intent);
}
```

or in Kotlin:

```kotlin
override fun onNewIntent(intent: Intent?) {
    super.onNewIntent(intent)
    processNewIntent(intent)
}
```
