### ISSUE TITLE
Intent 传递数据无需保存恢复

### ISSUE THREAD

**Issue by laozoucd** [enbandari/ActivityBuilder#4]
实测，通过 intent 传递的数据，在屏幕旋转后，系统会自动恢复。无需自己写代码保存和恢复数据。

**Comment by bennyhuo** [comment]
我明白你的意思，你是说会保存原始 Intent 会传进来的数据吧。如果你把 Intent 的数据赋值给一个变量，然后这个变量的值发生了变化呢？这时候旋转字段这个变量如果按照原来的 Intent 进行赋值，那么就出现问题吧？

**Comment by bennyhuo** [comment]
建议你试一下在 Activity 构造完成之后，尝试修改被注入的变量，然后再旋转屏幕，看下这些变量的值在保存和不保存之间有何差异~

issue 我先关掉了哈，如果还有问题，可以重新打开~
