### ISSUE TITLE
Support Coroutine

### ISSUE THREAD

**Issue by bennyhuo** [enbandari/ActivityBuilder#5]
Use coroutine await style code instead of callback.

**Comment by bennyhuo** [comment]
Make it target to 2.0. Maybe useful.

**Comment by huia939** [comment]
催更！！！

**Comment by bennyhuo** [comment]
这个还没想好呢。。。

**Comment by bennyhuo** [comment]
There is a lot of problems to work around, so remove this from roadmap.
