### ISSUE TITLE
代码混淆后传递参数为null

### ISSUE THREAD

**Issue by Zhao187** [enbandari/ActivityBuilder#8]
代码混淆后传递参数为null ,Optional使用后在代码混淆中为null

**Comment by bennyhuo** [comment]
生成的代码需要 keep，例如生成的 XXXBuilder 是不能混淆的，否则会导致找不到而无法注入哈~
等我有空了在项目里面提供一个混淆配置吧。

**Comment by bennyhuo** [comment]
2.0-beta4 已经添加了混淆配置，更新版本即可启用~
